// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/credit_enquiry_event/credit_enquiry_event.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreditEnquiryEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreditEnquiryEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreditEnquiryEvent with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreditEnquiryEventMultiError, or nil if none found.
func (m *CreditEnquiryEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *CreditEnquiryEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetId()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "Id",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSource()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "Source",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSpecVersion()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "SpecVersion",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetType()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "Type",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDataContentType()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "DataContentType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetDataSchema()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "DataSchema",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetSubject()) < 1 {
		err := CreditEnquiryEventValidationError{
			field:  "Subject",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetTime()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreditEnquiryEventValidationError{
					field:  "Time",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreditEnquiryEventValidationError{
					field:  "Time",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTime()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditEnquiryEventValidationError{
				field:  "Time",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetData() == nil {
		err := CreditEnquiryEventValidationError{
			field:  "Data",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreditEnquiryEventValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreditEnquiryEventValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreditEnquiryEventValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreditEnquiryEventMultiError(errors)
	}

	return nil
}

// CreditEnquiryEventMultiError is an error wrapping multiple validation errors
// returned by CreditEnquiryEvent.ValidateAll() if the designated constraints
// aren't met.
type CreditEnquiryEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreditEnquiryEventMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreditEnquiryEventMultiError) AllErrors() []error { return m }

// CreditEnquiryEventValidationError is the validation error returned by
// CreditEnquiryEvent.Validate if the designated constraints aren't met.
type CreditEnquiryEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreditEnquiryEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreditEnquiryEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreditEnquiryEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreditEnquiryEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreditEnquiryEventValidationError) ErrorName() string {
	return "CreditEnquiryEventValidationError"
}

// Error satisfies the builtin error interface
func (e CreditEnquiryEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreditEnquiryEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreditEnquiryEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreditEnquiryEventValidationError{}

// Validate checks the field values on CreditEnquiryEventData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreditEnquiryEventData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreditEnquiryEventData with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreditEnquiryEventDataMultiError, or nil if none found.
func (m *CreditEnquiryEventData) ValidateAll() error {
	return m.validate(true)
}

func (m *CreditEnquiryEventData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCreditEnquiryId()) < 1 {
		err := CreditEnquiryEventDataValidationError{
			field:  "CreditEnquiryId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetApplicationNumber()) < 1 {
		err := CreditEnquiryEventDataValidationError{
			field:  "ApplicationNumber",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetEnquiryState()) < 1 {
		err := CreditEnquiryEventDataValidationError{
			field:  "EnquiryState",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetLoanAmount() < 0 {
		err := CreditEnquiryEventDataValidationError{
			field:  "LoanAmount",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetLoanPurpose()) < 1 {
		err := CreditEnquiryEventDataValidationError{
			field:  "LoanPurpose",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetInitialStructureTermMonth() < 0 {
		err := CreditEnquiryEventDataValidationError{
			field:  "InitialStructureTermMonth",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTotalMonthlyNetIncomeAmount() < 0 {
		err := CreditEnquiryEventDataValidationError{
			field:  "TotalMonthlyNetIncomeAmount",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTotalAnnualGrossIncome() < 0 {
		err := CreditEnquiryEventDataValidationError{
			field:  "TotalAnnualGrossIncome",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTotalSavingsAmount() < 0 {
		err := CreditEnquiryEventDataValidationError{
			field:  "TotalSavingsAmount",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTotalNumberOfContinuingHomeLoans() < 0 {
		err := CreditEnquiryEventDataValidationError{
			field:  "TotalNumberOfContinuingHomeLoans",
			reason: "value must be greater than or equal to 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreditEnquiryEventDataMultiError(errors)
	}

	return nil
}

// CreditEnquiryEventDataMultiError is an error wrapping multiple validation
// errors returned by CreditEnquiryEventData.ValidateAll() if the designated
// constraints aren't met.
type CreditEnquiryEventDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreditEnquiryEventDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreditEnquiryEventDataMultiError) AllErrors() []error { return m }

// CreditEnquiryEventDataValidationError is the validation error returned by
// CreditEnquiryEventData.Validate if the designated constraints aren't met.
type CreditEnquiryEventDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreditEnquiryEventDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreditEnquiryEventDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreditEnquiryEventDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreditEnquiryEventDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreditEnquiryEventDataValidationError) ErrorName() string {
	return "CreditEnquiryEventDataValidationError"
}

// Error satisfies the builtin error interface
func (e CreditEnquiryEventDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreditEnquiryEventData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreditEnquiryEventDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreditEnquiryEventDataValidationError{}
