// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/sop/sop.proto

package sop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SOPRequest represents the request to get consolidated SOP data
type SOPRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CreditEnquiryId      string                 `protobuf:"bytes,1,opt,name=credit_enquiry_id,json=creditEnquiryId,proto3" json:"credit_enquiry_id,omitempty"`
	CreditEnquiryVersion string                 `protobuf:"bytes,2,opt,name=credit_enquiry_version,json=creditEnquiryVersion,proto3" json:"credit_enquiry_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SOPRequest) Reset() {
	*x = SOPRequest{}
	mi := &file_proto_sop_sop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOPRequest) ProtoMessage() {}

func (x *SOPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sop_sop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOPRequest.ProtoReflect.Descriptor instead.
func (*SOPRequest) Descriptor() ([]byte, []int) {
	return file_proto_sop_sop_proto_rawDescGZIP(), []int{0}
}

func (x *SOPRequest) GetCreditEnquiryId() string {
	if x != nil {
		return x.CreditEnquiryId
	}
	return ""
}

func (x *SOPRequest) GetCreditEnquiryVersion() string {
	if x != nil {
		return x.CreditEnquiryVersion
	}
	return ""
}

// SOPResponse represents the consolidated SOP data
type SOPResponse struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	SopAssessmentId                  string                 `protobuf:"bytes,1,opt,name=sop_assessment_id,json=sopAssessmentId,proto3" json:"sop_assessment_id,omitempty"`
	ServiceabilityAssessmentId       string                 `protobuf:"bytes,2,opt,name=serviceability_assessment_id,json=serviceabilityAssessmentId,proto3" json:"serviceability_assessment_id,omitempty"`
	TotalMonthlyNetIncomeAmount      float64                `protobuf:"fixed64,3,opt,name=total_monthly_net_income_amount,json=totalMonthlyNetIncomeAmount,proto3" json:"total_monthly_net_income_amount,omitempty"`
	TotalAnnualGrossIncome           float64                `protobuf:"fixed64,4,opt,name=total_annual_gross_income,json=totalAnnualGrossIncome,proto3" json:"total_annual_gross_income,omitempty"`
	TotalSavingsAmount               float64                `protobuf:"fixed64,5,opt,name=total_savings_amount,json=totalSavingsAmount,proto3" json:"total_savings_amount,omitempty"`
	TotalNumberOfContinuingHomeLoans int32                  `protobuf:"varint,6,opt,name=total_number_of_continuing_home_loans,json=totalNumberOfContinuingHomeLoans,proto3" json:"total_number_of_continuing_home_loans,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *SOPResponse) Reset() {
	*x = SOPResponse{}
	mi := &file_proto_sop_sop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SOPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SOPResponse) ProtoMessage() {}

func (x *SOPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sop_sop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SOPResponse.ProtoReflect.Descriptor instead.
func (*SOPResponse) Descriptor() ([]byte, []int) {
	return file_proto_sop_sop_proto_rawDescGZIP(), []int{1}
}

func (x *SOPResponse) GetSopAssessmentId() string {
	if x != nil {
		return x.SopAssessmentId
	}
	return ""
}

func (x *SOPResponse) GetServiceabilityAssessmentId() string {
	if x != nil {
		return x.ServiceabilityAssessmentId
	}
	return ""
}

func (x *SOPResponse) GetTotalMonthlyNetIncomeAmount() float64 {
	if x != nil {
		return x.TotalMonthlyNetIncomeAmount
	}
	return 0
}

func (x *SOPResponse) GetTotalAnnualGrossIncome() float64 {
	if x != nil {
		return x.TotalAnnualGrossIncome
	}
	return 0
}

func (x *SOPResponse) GetTotalSavingsAmount() float64 {
	if x != nil {
		return x.TotalSavingsAmount
	}
	return 0
}

func (x *SOPResponse) GetTotalNumberOfContinuingHomeLoans() int32 {
	if x != nil {
		return x.TotalNumberOfContinuingHomeLoans
	}
	return 0
}

var File_proto_sop_sop_proto protoreflect.FileDescriptor

const file_proto_sop_sop_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sop/sop.proto\x12\x03sop\"n\n" +
	"\n" +
	"SOPRequest\x12*\n" +
	"\x11credit_enquiry_id\x18\x01 \x01(\tR\x0fcreditEnquiryId\x124\n" +
	"\x16credit_enquiry_version\x18\x02 \x01(\tR\x14creditEnquiryVersion\"\xff\x02\n" +
	"\vSOPResponse\x12*\n" +
	"\x11sop_assessment_id\x18\x01 \x01(\tR\x0fsopAssessmentId\x12@\n" +
	"\x1cserviceability_assessment_id\x18\x02 \x01(\tR\x1aserviceabilityAssessmentId\x12D\n" +
	"\x1ftotal_monthly_net_income_amount\x18\x03 \x01(\x01R\x1btotalMonthlyNetIncomeAmount\x129\n" +
	"\x19total_annual_gross_income\x18\x04 \x01(\x01R\x16totalAnnualGrossIncome\x120\n" +
	"\x14total_savings_amount\x18\x05 \x01(\x01R\x12totalSavingsAmount\x12O\n" +
	"%total_number_of_continuing_home_loans\x18\x06 \x01(\x05R totalNumberOfContinuingHomeLoans2G\n" +
	"\n" +
	"SOPService\x129\n" +
	"\x12GetConsolidatedSOP\x12\x0f.sop.SOPRequest\x1a\x10.sop.SOPResponse\"\x00B\x1eZ\x1cgo-loan-service-v3/proto/sopb\x06proto3"

var (
	file_proto_sop_sop_proto_rawDescOnce sync.Once
	file_proto_sop_sop_proto_rawDescData []byte
)

func file_proto_sop_sop_proto_rawDescGZIP() []byte {
	file_proto_sop_sop_proto_rawDescOnce.Do(func() {
		file_proto_sop_sop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sop_sop_proto_rawDesc), len(file_proto_sop_sop_proto_rawDesc)))
	})
	return file_proto_sop_sop_proto_rawDescData
}

var file_proto_sop_sop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sop_sop_proto_goTypes = []any{
	(*SOPRequest)(nil),  // 0: sop.SOPRequest
	(*SOPResponse)(nil), // 1: sop.SOPResponse
}
var file_proto_sop_sop_proto_depIdxs = []int32{
	0, // 0: sop.SOPService.GetConsolidatedSOP:input_type -> sop.SOPRequest
	1, // 1: sop.SOPService.GetConsolidatedSOP:output_type -> sop.SOPResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sop_sop_proto_init() }
func file_proto_sop_sop_proto_init() {
	if File_proto_sop_sop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sop_sop_proto_rawDesc), len(file_proto_sop_sop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sop_sop_proto_goTypes,
		DependencyIndexes: file_proto_sop_sop_proto_depIdxs,
		MessageInfos:      file_proto_sop_sop_proto_msgTypes,
	}.Build()
	File_proto_sop_sop_proto = out.File
	file_proto_sop_sop_proto_goTypes = nil
	file_proto_sop_sop_proto_depIdxs = nil
}
