// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/sop/sop.proto

package sop

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SOPService_GetConsolidatedSOP_FullMethodName = "/sop.SOPService/GetConsolidatedSOP"
)

// SOPServiceClient is the client API for SOPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SOPService defines the interface for SOP-related operations
type SOPServiceClient interface {
	// GetConsolidatedSOP retrieves the consolidated Statement of Position
	GetConsolidatedSOP(ctx context.Context, in *SOPRequest, opts ...grpc.CallOption) (*SOPResponse, error)
}

type sOPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSOPServiceClient(cc grpc.ClientConnInterface) SOPServiceClient {
	return &sOPServiceClient{cc}
}

func (c *sOPServiceClient) GetConsolidatedSOP(ctx context.Context, in *SOPRequest, opts ...grpc.CallOption) (*SOPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SOPResponse)
	err := c.cc.Invoke(ctx, SOPService_GetConsolidatedSOP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SOPServiceServer is the server API for SOPService service.
// All implementations must embed UnimplementedSOPServiceServer
// for forward compatibility.
//
// SOPService defines the interface for SOP-related operations
type SOPServiceServer interface {
	// GetConsolidatedSOP retrieves the consolidated Statement of Position
	GetConsolidatedSOP(context.Context, *SOPRequest) (*SOPResponse, error)
	mustEmbedUnimplementedSOPServiceServer()
}

// UnimplementedSOPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSOPServiceServer struct{}

func (UnimplementedSOPServiceServer) GetConsolidatedSOP(context.Context, *SOPRequest) (*SOPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConsolidatedSOP not implemented")
}
func (UnimplementedSOPServiceServer) mustEmbedUnimplementedSOPServiceServer() {}
func (UnimplementedSOPServiceServer) testEmbeddedByValue()                    {}

// UnsafeSOPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SOPServiceServer will
// result in compilation errors.
type UnsafeSOPServiceServer interface {
	mustEmbedUnimplementedSOPServiceServer()
}

func RegisterSOPServiceServer(s grpc.ServiceRegistrar, srv SOPServiceServer) {
	// If the following call pancis, it indicates UnimplementedSOPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SOPService_ServiceDesc, srv)
}

func _SOPService_GetConsolidatedSOP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SOPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SOPServiceServer).GetConsolidatedSOP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SOPService_GetConsolidatedSOP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SOPServiceServer).GetConsolidatedSOP(ctx, req.(*SOPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SOPService_ServiceDesc is the grpc.ServiceDesc for SOPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SOPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sop.SOPService",
	HandlerType: (*SOPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConsolidatedSOP",
			Handler:    _SOPService_GetConsolidatedSOP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sop/sop.proto",
}
