// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: credit_enquiry.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditEnquiryRequest struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	RequestId                        []byte                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // UUID v4
	EnquiryState                     string                 `protobuf:"bytes,2,opt,name=enquiry_state,json=enquiryState,proto3" json:"enquiry_state,omitempty"`
	ApplicationNumber                string                 `protobuf:"bytes,3,opt,name=application_number,json=applicationNumber,proto3" json:"application_number,omitempty"`
	LoanAmount                       float64                `protobuf:"fixed64,4,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`
	LoanPurpose                      string                 `protobuf:"bytes,5,opt,name=loan_purpose,json=loanPurpose,proto3" json:"loan_purpose,omitempty"`
	InitialStructureTermMonth        int64                  `protobuf:"varint,6,opt,name=initial_structure_term_month,json=initialStructureTermMonth,proto3" json:"initial_structure_term_month,omitempty"`
	TotalMonthlyNetIncomeAmount      float64                `protobuf:"fixed64,7,opt,name=total_monthly_net_income_amount,json=totalMonthlyNetIncomeAmount,proto3" json:"total_monthly_net_income_amount,omitempty"`
	TotalAnnualGrossIncome           float64                `protobuf:"fixed64,8,opt,name=total_annual_gross_income,json=totalAnnualGrossIncome,proto3" json:"total_annual_gross_income,omitempty"`
	TotalSavingsAmount               float64                `protobuf:"fixed64,9,opt,name=total_savings_amount,json=totalSavingsAmount,proto3" json:"total_savings_amount,omitempty"`
	TotalNumberOfContinuingHomeLoans float64                `protobuf:"fixed64,10,opt,name=total_number_of_continuing_home_loans,json=totalNumberOfContinuingHomeLoans,proto3" json:"total_number_of_continuing_home_loans,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CreditEnquiryRequest) Reset() {
	*x = CreditEnquiryRequest{}
	mi := &file_credit_enquiry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditEnquiryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditEnquiryRequest) ProtoMessage() {}

func (x *CreditEnquiryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credit_enquiry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditEnquiryRequest.ProtoReflect.Descriptor instead.
func (*CreditEnquiryRequest) Descriptor() ([]byte, []int) {
	return file_credit_enquiry_proto_rawDescGZIP(), []int{0}
}

func (x *CreditEnquiryRequest) GetRequestId() []byte {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *CreditEnquiryRequest) GetEnquiryState() string {
	if x != nil {
		return x.EnquiryState
	}
	return ""
}

func (x *CreditEnquiryRequest) GetApplicationNumber() string {
	if x != nil {
		return x.ApplicationNumber
	}
	return ""
}

func (x *CreditEnquiryRequest) GetLoanAmount() float64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *CreditEnquiryRequest) GetLoanPurpose() string {
	if x != nil {
		return x.LoanPurpose
	}
	return ""
}

func (x *CreditEnquiryRequest) GetInitialStructureTermMonth() int64 {
	if x != nil {
		return x.InitialStructureTermMonth
	}
	return 0
}

func (x *CreditEnquiryRequest) GetTotalMonthlyNetIncomeAmount() float64 {
	if x != nil {
		return x.TotalMonthlyNetIncomeAmount
	}
	return 0
}

func (x *CreditEnquiryRequest) GetTotalAnnualGrossIncome() float64 {
	if x != nil {
		return x.TotalAnnualGrossIncome
	}
	return 0
}

func (x *CreditEnquiryRequest) GetTotalSavingsAmount() float64 {
	if x != nil {
		return x.TotalSavingsAmount
	}
	return 0
}

func (x *CreditEnquiryRequest) GetTotalNumberOfContinuingHomeLoans() float64 {
	if x != nil {
		return x.TotalNumberOfContinuingHomeLoans
	}
	return 0
}

var File_credit_enquiry_proto protoreflect.FileDescriptor

const file_credit_enquiry_proto_rawDesc = "" +
	"\n" +
	"\x14credit_enquiry.proto\x12\rcreditenquiry\x1aAgithub.com/envoyproxy/protoc-gen-validate/validate/validate.proto\"\x9d\x04\n" +
	"\x14CreditEnquiryRequest\x12(\n" +
	"\n" +
	"request_id\x18\x01 \x01(\fB\t\xfaB\x06z\x04h\x10p\x01R\trequestId\x12#\n" +
	"\renquiry_state\x18\x02 \x01(\tR\fenquiryState\x12-\n" +
	"\x12application_number\x18\x03 \x01(\tR\x11applicationNumber\x12\x1f\n" +
	"\vloan_amount\x18\x04 \x01(\x01R\n" +
	"loanAmount\x12!\n" +
	"\floan_purpose\x18\x05 \x01(\tR\vloanPurpose\x12?\n" +
	"\x1cinitial_structure_term_month\x18\x06 \x01(\x03R\x19initialStructureTermMonth\x12D\n" +
	"\x1ftotal_monthly_net_income_amount\x18\a \x01(\x01R\x1btotalMonthlyNetIncomeAmount\x129\n" +
	"\x19total_annual_gross_income\x18\b \x01(\x01R\x16totalAnnualGrossIncome\x120\n" +
	"\x14total_savings_amount\x18\t \x01(\x01R\x12totalSavingsAmount\x12O\n" +
	"%total_number_of_continuing_home_loans\x18\n" +
	" \x01(\x01R totalNumberOfContinuingHomeLoansB\x1aZ\x18go-loan-service-v3/protob\x06proto3"

var (
	file_credit_enquiry_proto_rawDescOnce sync.Once
	file_credit_enquiry_proto_rawDescData []byte
)

func file_credit_enquiry_proto_rawDescGZIP() []byte {
	file_credit_enquiry_proto_rawDescOnce.Do(func() {
		file_credit_enquiry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credit_enquiry_proto_rawDesc), len(file_credit_enquiry_proto_rawDesc)))
	})
	return file_credit_enquiry_proto_rawDescData
}

var file_credit_enquiry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_credit_enquiry_proto_goTypes = []any{
	(*CreditEnquiryRequest)(nil), // 0: creditenquiry.CreditEnquiryRequest
}
var file_credit_enquiry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_credit_enquiry_proto_init() }
func file_credit_enquiry_proto_init() {
	if File_credit_enquiry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credit_enquiry_proto_rawDesc), len(file_credit_enquiry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_credit_enquiry_proto_goTypes,
		DependencyIndexes: file_credit_enquiry_proto_depIdxs,
		MessageInfos:      file_credit_enquiry_proto_msgTypes,
	}.Build()
	File_credit_enquiry_proto = out.File
	file_credit_enquiry_proto_goTypes = nil
	file_credit_enquiry_proto_depIdxs = nil
}
