// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/credit_enquiry_event.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreditEnquiryEvent represents a CloudEvent for credit enquiry creation
type CreditEnquiryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CloudEvent attributes
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                    // ce-id
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                                            // ce-source
	SpecVersion     string                 `protobuf:"bytes,3,opt,name=spec_version,json=specVersion,proto3" json:"spec_version,omitempty"`               // ce-specversion
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                                // ce-type
	DataContentType string                 `protobuf:"bytes,5,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"` // ce-datacontenttype
	DataSchema      string                 `protobuf:"bytes,6,opt,name=data_schema,json=dataSchema,proto3" json:"data_schema,omitempty"`                  // ce-dataschema
	Subject         string                 `protobuf:"bytes,7,opt,name=subject,proto3" json:"subject,omitempty"`                                          // ce-subject
	Time            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`                                                // ce-time
	// Event data
	Data          *CreditEnquiryEventData `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditEnquiryEvent) Reset() {
	*x = CreditEnquiryEvent{}
	mi := &file_proto_credit_enquiry_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditEnquiryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditEnquiryEvent) ProtoMessage() {}

func (x *CreditEnquiryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credit_enquiry_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditEnquiryEvent.ProtoReflect.Descriptor instead.
func (*CreditEnquiryEvent) Descriptor() ([]byte, []int) {
	return file_proto_credit_enquiry_event_proto_rawDescGZIP(), []int{0}
}

func (x *CreditEnquiryEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreditEnquiryEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreditEnquiryEvent) GetSpecVersion() string {
	if x != nil {
		return x.SpecVersion
	}
	return ""
}

func (x *CreditEnquiryEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreditEnquiryEvent) GetDataContentType() string {
	if x != nil {
		return x.DataContentType
	}
	return ""
}

func (x *CreditEnquiryEvent) GetDataSchema() string {
	if x != nil {
		return x.DataSchema
	}
	return ""
}

func (x *CreditEnquiryEvent) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreditEnquiryEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *CreditEnquiryEvent) GetData() *CreditEnquiryEventData {
	if x != nil {
		return x.Data
	}
	return nil
}

// CreditEnquiryEventData contains the actual event payload
type CreditEnquiryEventData struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	CreditEnquiryId                  string                 `protobuf:"bytes,1,opt,name=credit_enquiry_id,json=creditEnquiryId,proto3" json:"credit_enquiry_id,omitempty"`
	ApplicationNumber                string                 `protobuf:"bytes,2,opt,name=application_number,json=applicationNumber,proto3" json:"application_number,omitempty"`
	EnquiryState                     string                 `protobuf:"bytes,3,opt,name=enquiry_state,json=enquiryState,proto3" json:"enquiry_state,omitempty"`
	LoanAmount                       float64                `protobuf:"fixed64,4,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`
	LoanPurpose                      string                 `protobuf:"bytes,5,opt,name=loan_purpose,json=loanPurpose,proto3" json:"loan_purpose,omitempty"`
	InitialStructureTermMonth        int64                  `protobuf:"varint,6,opt,name=initial_structure_term_month,json=initialStructureTermMonth,proto3" json:"initial_structure_term_month,omitempty"`
	TotalMonthlyNetIncomeAmount      float64                `protobuf:"fixed64,7,opt,name=total_monthly_net_income_amount,json=totalMonthlyNetIncomeAmount,proto3" json:"total_monthly_net_income_amount,omitempty"`
	TotalAnnualGrossIncome           float64                `protobuf:"fixed64,8,opt,name=total_annual_gross_income,json=totalAnnualGrossIncome,proto3" json:"total_annual_gross_income,omitempty"`
	TotalSavingsAmount               float64                `protobuf:"fixed64,9,opt,name=total_savings_amount,json=totalSavingsAmount,proto3" json:"total_savings_amount,omitempty"`
	TotalNumberOfContinuingHomeLoans int64                  `protobuf:"varint,10,opt,name=total_number_of_continuing_home_loans,json=totalNumberOfContinuingHomeLoans,proto3" json:"total_number_of_continuing_home_loans,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CreditEnquiryEventData) Reset() {
	*x = CreditEnquiryEventData{}
	mi := &file_proto_credit_enquiry_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditEnquiryEventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditEnquiryEventData) ProtoMessage() {}

func (x *CreditEnquiryEventData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credit_enquiry_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditEnquiryEventData.ProtoReflect.Descriptor instead.
func (*CreditEnquiryEventData) Descriptor() ([]byte, []int) {
	return file_proto_credit_enquiry_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreditEnquiryEventData) GetCreditEnquiryId() string {
	if x != nil {
		return x.CreditEnquiryId
	}
	return ""
}

func (x *CreditEnquiryEventData) GetApplicationNumber() string {
	if x != nil {
		return x.ApplicationNumber
	}
	return ""
}

func (x *CreditEnquiryEventData) GetEnquiryState() string {
	if x != nil {
		return x.EnquiryState
	}
	return ""
}

func (x *CreditEnquiryEventData) GetLoanAmount() float64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *CreditEnquiryEventData) GetLoanPurpose() string {
	if x != nil {
		return x.LoanPurpose
	}
	return ""
}

func (x *CreditEnquiryEventData) GetInitialStructureTermMonth() int64 {
	if x != nil {
		return x.InitialStructureTermMonth
	}
	return 0
}

func (x *CreditEnquiryEventData) GetTotalMonthlyNetIncomeAmount() float64 {
	if x != nil {
		return x.TotalMonthlyNetIncomeAmount
	}
	return 0
}

func (x *CreditEnquiryEventData) GetTotalAnnualGrossIncome() float64 {
	if x != nil {
		return x.TotalAnnualGrossIncome
	}
	return 0
}

func (x *CreditEnquiryEventData) GetTotalSavingsAmount() float64 {
	if x != nil {
		return x.TotalSavingsAmount
	}
	return 0
}

func (x *CreditEnquiryEventData) GetTotalNumberOfContinuingHomeLoans() int64 {
	if x != nil {
		return x.TotalNumberOfContinuingHomeLoans
	}
	return 0
}

var File_proto_credit_enquiry_event_proto protoreflect.FileDescriptor

const file_proto_credit_enquiry_event_proto_rawDesc = "" +
	"\n" +
	" proto/credit_enquiry_event.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\x86\x03\n" +
	"\x12CreditEnquiryEvent\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x02id\x12\x1f\n" +
	"\x06source\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06source\x12*\n" +
	"\fspec_version\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vspecVersion\x12\x1b\n" +
	"\x04type\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04type\x123\n" +
	"\x11data_content_type\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fdataContentType\x12(\n" +
	"\vdata_schema\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"dataSchema\x12!\n" +
	"\asubject\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\asubject\x12.\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12;\n" +
	"\x04data\x18\t \x01(\v2\x1d.proto.CreditEnquiryEventDataB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x04data\"\x97\x05\n" +
	"\x16CreditEnquiryEventData\x123\n" +
	"\x11credit_enquiry_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fcreditEnquiryId\x126\n" +
	"\x12application_number\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x11applicationNumber\x12,\n" +
	"\renquiry_state\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\fenquiryState\x12/\n" +
	"\vloan_amount\x18\x04 \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\n" +
	"loanAmount\x12*\n" +
	"\floan_purpose\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\vloanPurpose\x12H\n" +
	"\x1cinitial_structure_term_month\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x19initialStructureTermMonth\x12T\n" +
	"\x1ftotal_monthly_net_income_amount\x18\a \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x1btotalMonthlyNetIncomeAmount\x12I\n" +
	"\x19total_annual_gross_income\x18\b \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x16totalAnnualGrossIncome\x12@\n" +
	"\x14total_savings_amount\x18\t \x01(\x01B\x0e\xfaB\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\x12totalSavingsAmount\x12X\n" +
	"%total_number_of_continuing_home_loans\x18\n" +
	" \x01(\x03B\a\xfaB\x04\"\x02(\x00R totalNumberOfContinuingHomeLoansB\x1aZ\x18go-loan-service-v3/protob\x06proto3"

var (
	file_proto_credit_enquiry_event_proto_rawDescOnce sync.Once
	file_proto_credit_enquiry_event_proto_rawDescData []byte
)

func file_proto_credit_enquiry_event_proto_rawDescGZIP() []byte {
	file_proto_credit_enquiry_event_proto_rawDescOnce.Do(func() {
		file_proto_credit_enquiry_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_credit_enquiry_event_proto_rawDesc), len(file_proto_credit_enquiry_event_proto_rawDesc)))
	})
	return file_proto_credit_enquiry_event_proto_rawDescData
}

var file_proto_credit_enquiry_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_credit_enquiry_event_proto_goTypes = []any{
	(*CreditEnquiryEvent)(nil),     // 0: proto.CreditEnquiryEvent
	(*CreditEnquiryEventData)(nil), // 1: proto.CreditEnquiryEventData
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_proto_credit_enquiry_event_proto_depIdxs = []int32{
	2, // 0: proto.CreditEnquiryEvent.time:type_name -> google.protobuf.Timestamp
	1, // 1: proto.CreditEnquiryEvent.data:type_name -> proto.CreditEnquiryEventData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_credit_enquiry_event_proto_init() }
func file_proto_credit_enquiry_event_proto_init() {
	if File_proto_credit_enquiry_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_credit_enquiry_event_proto_rawDesc), len(file_proto_credit_enquiry_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_credit_enquiry_event_proto_goTypes,
		DependencyIndexes: file_proto_credit_enquiry_event_proto_depIdxs,
		MessageInfos:      file_proto_credit_enquiry_event_proto_msgTypes,
	}.Build()
	File_proto_credit_enquiry_event_proto = out.File
	file_proto_credit_enquiry_event_proto_goTypes = nil
	file_proto_credit_enquiry_event_proto_depIdxs = nil
}
