// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/credit_enquiry.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreditEnquiryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreditEnquiryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreditEnquiryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreditEnquiryRequestMultiError, or nil if none found.
func (m *CreditEnquiryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreditEnquiryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(m.GetRequestId()) != 16 {
		err := CreditEnquiryRequestValidationError{
			field:  "RequestId",
			reason: "value length must be 16 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for EnquiryState

	// no validation rules for ApplicationNumber

	// no validation rules for LoanAmount

	// no validation rules for LoanPurpose

	// no validation rules for InitialStructureTermMonth

	// no validation rules for TotalMonthlyNetIncomeAmount

	// no validation rules for TotalAnnualGrossIncome

	// no validation rules for TotalSavingsAmount

	// no validation rules for TotalNumberOfContinuingHomeLoans

	// no validation rules for ProductName

	// no validation rules for ProductCode

	if len(errors) > 0 {
		return CreditEnquiryRequestMultiError(errors)
	}

	return nil
}

// CreditEnquiryRequestMultiError is an error wrapping multiple validation
// errors returned by CreditEnquiryRequest.ValidateAll() if the designated
// constraints aren't met.
type CreditEnquiryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreditEnquiryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreditEnquiryRequestMultiError) AllErrors() []error { return m }

// CreditEnquiryRequestValidationError is the validation error returned by
// CreditEnquiryRequest.Validate if the designated constraints aren't met.
type CreditEnquiryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreditEnquiryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreditEnquiryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreditEnquiryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreditEnquiryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreditEnquiryRequestValidationError) ErrorName() string {
	return "CreditEnquiryRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreditEnquiryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreditEnquiryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreditEnquiryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreditEnquiryRequestValidationError{}

// Validate checks the field values on CreditEnquiryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreditEnquiryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreditEnquiryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreditEnquiryResponseMultiError, or nil if none found.
func (m *CreditEnquiryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreditEnquiryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return CreditEnquiryResponseMultiError(errors)
	}

	return nil
}

// CreditEnquiryResponseMultiError is an error wrapping multiple validation
// errors returned by CreditEnquiryResponse.ValidateAll() if the designated
// constraints aren't met.
type CreditEnquiryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreditEnquiryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreditEnquiryResponseMultiError) AllErrors() []error { return m }

// CreditEnquiryResponseValidationError is the validation error returned by
// CreditEnquiryResponse.Validate if the designated constraints aren't met.
type CreditEnquiryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreditEnquiryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreditEnquiryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreditEnquiryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreditEnquiryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreditEnquiryResponseValidationError) ErrorName() string {
	return "CreditEnquiryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreditEnquiryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreditEnquiryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreditEnquiryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreditEnquiryResponseValidationError{}
