// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/product_assessment.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductAssessmentService_GetProductRate_FullMethodName = "/proto.ProductAssessmentService/GetProductRate"
)

// ProductAssessmentServiceClient is the client API for ProductAssessmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProductAssessmentService defines the service for product assessment
type ProductAssessmentServiceClient interface {
	// GetProductRate retrieves the product rate from product service
	GetProductRate(ctx context.Context, in *ProductRateRequest, opts ...grpc.CallOption) (*ProductRateResponse, error)
}

type productAssessmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductAssessmentServiceClient(cc grpc.ClientConnInterface) ProductAssessmentServiceClient {
	return &productAssessmentServiceClient{cc}
}

func (c *productAssessmentServiceClient) GetProductRate(ctx context.Context, in *ProductRateRequest, opts ...grpc.CallOption) (*ProductRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProductRateResponse)
	err := c.cc.Invoke(ctx, ProductAssessmentService_GetProductRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductAssessmentServiceServer is the server API for ProductAssessmentService service.
// All implementations must embed UnimplementedProductAssessmentServiceServer
// for forward compatibility.
//
// ProductAssessmentService defines the service for product assessment
type ProductAssessmentServiceServer interface {
	// GetProductRate retrieves the product rate from product service
	GetProductRate(context.Context, *ProductRateRequest) (*ProductRateResponse, error)
	mustEmbedUnimplementedProductAssessmentServiceServer()
}

// UnimplementedProductAssessmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductAssessmentServiceServer struct{}

func (UnimplementedProductAssessmentServiceServer) GetProductRate(context.Context, *ProductRateRequest) (*ProductRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductRate not implemented")
}
func (UnimplementedProductAssessmentServiceServer) mustEmbedUnimplementedProductAssessmentServiceServer() {
}
func (UnimplementedProductAssessmentServiceServer) testEmbeddedByValue() {}

// UnsafeProductAssessmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductAssessmentServiceServer will
// result in compilation errors.
type UnsafeProductAssessmentServiceServer interface {
	mustEmbedUnimplementedProductAssessmentServiceServer()
}

func RegisterProductAssessmentServiceServer(s grpc.ServiceRegistrar, srv ProductAssessmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductAssessmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductAssessmentService_ServiceDesc, srv)
}

func _ProductAssessmentService_GetProductRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductAssessmentServiceServer).GetProductRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductAssessmentService_GetProductRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductAssessmentServiceServer).GetProductRate(ctx, req.(*ProductRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductAssessmentService_ServiceDesc is the grpc.ServiceDesc for ProductAssessmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductAssessmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductAssessmentService",
	HandlerType: (*ProductAssessmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductRate",
			Handler:    _ProductAssessmentService_GetProductRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product_assessment.proto",
}
